# Generated by Django 4.2.11 on 2024-04-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='landmark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Landmark',
        ),
    ]
