# Generated by Django 4.2.11 on 2024-04-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0008_alter_land_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
