# Generated by Django 4.2.11 on 2024-04-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0010_alter_land_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='area',
        ),
    ]
