# Generated by Django 4.2.11 on 2024-04-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0011_remove_land_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='area',
            field=models.FloatField(default=None),
        ),
    ]
