# Generated by Django 4.2.11 on 2024-04-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0013_alter_land_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='area',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20),
        ),
    ]
